version: '2'

networks:
  default:
    ipam:
      config:
        - subnet:   192.168.132.0/24 # In order to specify static IPs, we must explicitly declare subnet.
          ip_range: 192.168.132.128/25 # Range for dynamic IPs. We'll make sure to assign static IPs outside this range.

services:
  dnsmasq:
    image: ghcr.io/acbgbca/dnsmasq:latest@sha256:4b87d81828ace5d47879481bb0453ff3c8601347bf2545db7bce3ba8877f85b4
    environment:
      - |
        DNSMASQ_CONF=
        address=/local/192.168.132.5
        address=/internal/192.168.132.5
        address=/homelab/192.168.132.5
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 192.168.132.2

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:3.0.1-ubuntu@sha256:bb779775cfc7d2e65f9b0f80f17770878f5a50c00d15cc873b627c5c214ce37e
    volumes:
      - ../..:/workspaces
      - k3s-config:/k3s/config
      - k3s-data:/k3s/data
      - k3s-manifests:/k3s/manifests
    command: sleep infinity
    network_mode: service:k3s

  k3s:
    image: "rancher/k3s:v1.36.1-k3s1@sha256:08fdebd14db9ab7d5ea821d5bfa95d02341a6ef886842fcc8d9dfd0e9fa9e0cd"
    command: server
    environment:
      - K3S_NODE_NAME=k3s
      - K3S_KUBECONFIG_MODE=644
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    volumes:
    - k3s-data:/var/lib/rancher/k3s
    - k3s-config:/etc/rancher/k3s
    - k3s-manifests:/var/lib/rancher/k3s/server/manifests
    ports:
    - 6443:6443
    - 8080:80
    - 8443:443
    networks:
      default:
        ipv4_address: 192.168.132.5
    dns:
      - 192.168.132.2

  chromium:
    image: 'ghcr.io/linuxserver/chromium:latest@sha256:9ffa7e1457001348ee74ddf43dbcdc3d8d06bdf51412124f7a9360e227e1a496'
    container_name: chromium
    ports:
      - 3000:6901
    shm_size: "1gb"
    dns:
      - 192.168.132.2

volumes:
  k3s-config:
  k3s-data:
  k3s-manifests: