version: '2'

networks:
  default:
    ipam:
      config:
        - subnet:   192.168.132.0/24 # In order to specify static IPs, we must explicitly declare subnet.
          ip_range: 192.168.132.128/25 # Range for dynamic IPs. We'll make sure to assign static IPs outside this range.

services:
  dnsmasq:
    image: ghcr.io/acbgbca/dnsmasq:latest@sha256:3c8c9c292b370e0d675395246970a53658803c7d14baab2d8ab2988e2cb18c77
    environment:
      - |
        DNSMASQ_CONF=
        address=/local/192.168.132.5
        address=/internal/192.168.132.5
        address=/homelab/192.168.132.5
    cap_add:
      - NET_ADMIN
    networks:
      default:
        ipv4_address: 192.168.132.2

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:3.0.8-ubuntu@sha256:edfb983aab9c579a385dc23c57d7d3703f5ec920124d99c16204a2cac465aab4
    volumes:
      - ../..:/workspaces
      - k3s-config:/k3s/config
      - k3s-data:/k3s/data
      - k3s-manifests:/k3s/manifests
    command: sleep infinity
    network_mode: service:k3s

  k3s:
    image: "rancher/k3s:v1.36.4-k3s1@sha256:edad48e12bf81c3a09ac1c05c0c0ffaaa22145980b989d6fae84543a76b83657"
    command: server
    environment:
      - K3S_NODE_NAME=k3s
      - K3S_KUBECONFIG_MODE=644
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    volumes:
    - k3s-data:/var/lib/rancher/k3s
    - k3s-config:/etc/rancher/k3s
    - k3s-manifests:/var/lib/rancher/k3s/server/manifests
    ports:
    - 6443:6443
    - 8080:80
    - 8443:443
    networks:
      default:
        ipv4_address: 192.168.132.5
    dns:
      - 192.168.132.2

  chromium:
    image: 'ghcr.io/linuxserver/chromium:latest@sha256:54a61718733c82ac041e7c84543283419b06ab0d6439eef5c20b1f6a53b8dcd0'
    container_name: chromium
    ports:
      - 3000:6901
    shm_size: "1gb"
    dns:
      - 192.168.132.2

volumes:
  k3s-config:
  k3s-data:
  k3s-manifests: